apiVersion: v1
kind: Pod
metadata:
  name: giropops-1
  labels:
    app: worker
spec:
  containers:
  - name: worker-container-1
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: giropops-2
  labels:
    app: worker
spec:
  containers:
  - name: worker-container-2
    image: nginx:latest
    ports:
    - containerPort: 80
