apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ziiklinux
  name: ziiklinux
spec:
  containers:
  - image: nginx
    name: ziiklinux
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
