apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app: webserver-pod
  ports:
  - name: apache-port
    port: 80
    targetPort: 80
  - name: nginx-port
    port: 8080
    targetPort: 8080
  type: ClusterIP
