apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
spec:
  containers:
  - name: apache
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8080
    command: ["nginx", "-g", "daemon off;"]
    volumeMounts:
      - name: nginx-config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
